### ISSUE TITLE
AttributeError in BinaryParser.py

### ISSUE THREAD

**Issue by hiddenillusion** [williballenthin/shellbags#16]
The issue is within *ParseException* & *OverrunBufferException*. They both reference '_value' which isn't set (note - the line numbers might be off). 

```
Traceback (most recent call last):
  File "c:\python27\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "c:\python27\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "c:\python27\lib\logging\__init__.py", line 471, in format
    record.message = record.getMessage()
  File "c:\python27\lib\logging\__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "BinaryParser.py", line 111, in __str__
    return str(unicode(self))
  File "BinaryParser.py", line 114, in __unicode__
    return u"Tried to parse beyond the end of the file (%s)" % (self._value)
AttributeError: 'OverrunBufferException' object has no attribute '_value'
```
Staying consistent with *BinaryParserException*, *ParseException* & *OverrunBufferException* from INDXParse's BinaryParser.py (https://github.com/williballenthin/INDXParse/blob/master/BinaryParser.py) works:

```
class BinaryParserException(Exception):
	"""
	Base Exception class for binary parsing.
	"""
	def __init__(self, value):
		"""
		Constructor.
		Arguments:
		- `value`: A string description.
		"""
		super(BinaryParserException, self).__init__()
		self._value = value

	def __repr__(self):
		return "BinaryParserException(%r)" % (self._value)

	def __str__(self):
		return "Binary Parser Exception: %s" % (self._value)
		
class ParseException(BinaryParserException):
	"""
	An exception to be thrown during parsing, such as
	when an invalid header is encountered.
	"""
	def __init__(self, value):
		"""
		Constructor.
		Arguments:
		- `value`: A string description.
		"""
		super(ParseException, self).__init__(value)

	def __str__(self):
		return "Parse Exception(%s)" % (self._value)

	def __unicode__(self):
		return u"Parse Exception(%s)" % (self._value)

class OverrunBufferException(ParseException):
	"""
	An exception to be thrown during parsing when something is unpack into
	or from a location beyond the boundaries of a buffer.
	"""
	def __init__(self, readOffs, bufLen):
		tvalue = "read: %s, buffer length: %s" % (hex(readOffs), hex(bufLen))
		super(ParseException, self).__init__(tvalue)

	def __str__(self):
		return "Tried to parse beyond the end of the file (%s)" % (self._value)

	def __unicode__(self):
		return u"Tried to parse beyond the end of the file (%s)" % (self._value)
```

and produces the expected error message:
`Tried to parse beyond the end of the file (read: 0x70, buffer length: 0x70)`

**Comment by williballenthin** [comment]
Great catch! I've committed changes to `BinaryParser.py` that should fix this error. Please continue to open issues as you find them!
